/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MiniRouteImport } from './routes/mini'
import { Route as MiniAppRouteImport } from './routes/mini-app'
import { Route as ApiPublicMiniRouteImport } from './routes/api/public/mini'
import { Route as ApiPublicWorkerRouteImport } from './routes/api/public/worker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniRoute = MiniRouteImport.update({
  id: '/mini',
  path: '/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniAppRoute = MiniAppRouteImport.update({
  id: '/mini-app',
  path: '/mini-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMiniRoute = ApiPublicMiniRouteImport.update({
  id: '/api/public/mini',
  path: '/api/public/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerRoute = ApiPublicWorkerRouteImport.update({
  id: '/api/public/worker',
  path: '/api/public/worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mini': typeof MiniRoute
  '/mini-app': typeof MiniAppRoute
  '/api/public/mini': typeof ApiPublicMiniRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mini': typeof MiniRoute
  '/mini-app': typeof MiniAppRoute
  '/api/public/mini': typeof ApiPublicMiniRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mini': typeof MiniRoute
  '/mini-app': typeof MiniAppRoute
  '/api/public/mini': typeof ApiPublicMiniRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mini'
    | '/mini-app'
    | '/api/public/mini'
    | '/api/public/worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mini'
    | '/mini-app'
    | '/api/public/mini'
    | '/api/public/worker'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mini'
    | '/mini-app'
    | '/api/public/mini'
    | '/api/public/worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MiniRoute: typeof MiniRoute
  MiniAppRoute: typeof MiniAppRoute
  ApiPublicMiniRoute: typeof ApiPublicMiniRoute
  ApiPublicWorkerRoute: typeof ApiPublicWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini': {
      id: '/mini'
      path: '/mini'
      fullPath: '/mini'
      preLoaderRoute: typeof MiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-app': {
      id: '/mini-app'
      path: '/mini-app'
      fullPath: '/mini-app'
      preLoaderRoute: typeof MiniAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mini': {
      id: '/api/public/mini'
      path: '/api/public/mini'
      fullPath: '/api/public/mini'
      preLoaderRoute: typeof ApiPublicMiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker': {
      id: '/api/public/worker'
      path: '/api/public/worker'
      fullPath: '/api/public/worker'
      preLoaderRoute: typeof ApiPublicWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MiniRoute: MiniRoute,
  MiniAppRoute: MiniAppRoute,
  ApiPublicMiniRoute: ApiPublicMiniRoute,
  ApiPublicWorkerRoute: ApiPublicWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
